### ISSUE TITLE
Center offset

### ISSUE THREAD

**Issue by lethorable** [SDFIdk/vector_tiles_frontend#6]
Hej,

I config eksemplet (config.example.js) er forskellige variable defineret, bl.a. projektion (UTM32, etrs89), zoom level (7) og center koordinat for kortet (590000, 6205000)

Når man kører demoen, bliver kortet centreret pænt om Århus, som ubestridt er en pæn by og anerkendt af eksperter for at have det mest fairplayende fodboldhold i Superligaen. Dette harmonerer dog ikke helt med den angivne centerkoordinat. Kortets center (når man loader i en browser) er ca. ved Bering Kirkeby (566100, 6217900), ca. 24 km vest for og 13 km syd for den koordinat, der er defineret. 

Er der en grund til dette? Noget jeg har misset? :-) 

Mvh Thorbjørn

```
const config = {
  // API TOKEN can be aquired from https://dataforsyningen.dk/
  // When using the internal servers directly, the token can be set to an empty string to avoid adding the header.
  API_TOKEN: '[ INSERT TOKEN ]',
  API_VECTOR_TILES_BASEURL: 'https://api.dataforsyningen.dk/rest/skaermkort_vector_tiles/v1.0',
  PROJECTION_NAME: 'EPSG:25832',
  PROJECTION: '+proj=utm +zone=32 +ellps=GRS80 +units=m +no_defs',
  EXTENT: [120000, 5900000, 1000000, 6500000],
  CENTER: [590000, 6205000],
  ZOOM: 7,
  MAX_ZOOM: 15
}
```

**Comment by Gebuz** [comment]
Hej Thorbjørn

Tak for henvendelsen. Det har du ret i ser lidt funky ud. Jeg kigger på hvad det kan skyldes.

**Comment by Gebuz** [comment]
@lethorable Problemet skyldes at resolutions er forkert sat. Problemet er løst i v2.0.0, men hvis du vil fikse det i v1.0.0 kan du sætte `resolutions` i `index.js` til `[3276.8, 1638.4, 819.2, 409.6, 204.8, 102.4, 51.2, 25.6, 12.8, 6.4, 3.2, 1.6, 0.8, 0.4, 0.2, 0.1]`
på den her linje:
https://github.com/SDFIdk/vector_tiles_frontend/blob/c0ab2f1792cc2d48c91faad05eaf5176e15a8029/src/index.js#L35
